### PR TITLE
CoffeeScript -> JS & Incorporate most of PR #5

### PR DESCRIPTION
**Pull request by stdavis**
Not sure if you are up for this big of a change. I'm doing it in preparation for implementing #2. Let me know what I can do to make this palatable for you.

Thanks for the fun project!

### CODE REVIEW

**Comment by stdavis** [comment]
Hey @codeimpossible: Does this even have a possibility of being accepted? If so, I'll rebase against master and fix all of the conflicts. If not, I totally understand and I'll just close this. Thanks for the awesome project. It was a great learning experience for me.

Have a great weekend!

**Comment by codeimpossible** [comment]
@stdavis Yeah I like the idea of converting the code to straight up javascript, the only thing I'm slightly wary of is the eslint config coming from your org. I'm just not familiar with what it's enforcing, I've forked off of the http://github.com/airbnb/javascript set before, is this pretty similar?

**Comment by stdavis** [comment]
Oh ya. I was going to remove that. I can switch it to the airbnb preset...

**Comment by codeimpossible** [comment]
@stdavis cool, thanks for switching to the airbnb eslint set. I just got back from a company trip so I'll take a look at this this weekend!

**Comment by stdavis** [comment]
Anything else that I can do to make this mergeable? I've been using it for a month and it's been working great for me. I love it and would love to see others benefit from it.

**Comment by codeimpossible** [comment]
@stdavis nope, sorry I've just gotten tied up with some stuff, I'll plan to merge this tomorrow (well, technically today - monday) (for real)

**Comment by stdavis** [comment]
No worries. Just wanted to make sure that I wasn't holding up the process.

**Pull request merged**
