### PR TITLE
Switch from freegeoip.net to ip-api.com for geo ip request

### PR DESCRIPTION
**Pull request by stdavis**
The freegeoip.net service was shut off yesterday. This service is used by this package to get a lat/long from the IP of the local machine.

This PR upgrades this package to use their new service, ipstack.com. The only caveat is that they now require an API key. I went ahead and registered for a free tier account (10,000 calls per month) and hard-coded my key into the request. Not ideal, but I wasn't sure what another option would be. I can always reset my key if someone decides to steal it and bumps up the usage above the free tier.

I'm happy to update this PR with a different API key if you would like. I'm just trying to fix this package ASAP since it generates an annoying error message on atom startup.

### CODE REVIEW

**Comment by stdavis** [comment]
Here's another option that appears to not have an API key requirement: http://ip-api.com/docs/api:json

I can look into this more tomorrow...

**Comment by stdavis** [comment]
I switched this PR to ip-api.com. It does not require an API key and has much more suitable rate limits (150 requests per minute per IP address). This is ready for a review, @codeimpossible.

Ref: http://ip-api.com/docs/

**Comment by stdavis** [comment]
npm or yarn? Just noticed the yarn lock file. I typically use npm but am happy to use yarn if you prefer. We should probably remove `package-lock.json` or `yarn.lock`. Just let me know which one and I'll remove it.

**Comment by codeimpossible** [comment]
Wow, awesome! This looks good, going to merge to `dev` then cut a release and merge to master.

**Comment by stdavis** [comment]
Thanks!

**Pull request merged**
